"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Api
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class ApplicationInstance(InstanceResource):
    """
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Application resource.
    :ivar api_version: The API version used to start a new TwiML session.
    :ivar date_created: The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar date_updated: The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar friendly_name: The string that you assigned to describe the resource.
    :ivar message_status_callback: The URL we call using a POST method to send message status information to your application.
    :ivar sid: The unique string that that we created to identify the Application resource.
    :ivar sms_fallback_method: The HTTP method we use to call `sms_fallback_url`. Can be: `GET` or `POST`.
    :ivar sms_fallback_url: The URL that we call when an error occurs while retrieving or executing the TwiML from `sms_url`.
    :ivar sms_method: The HTTP method we use to call `sms_url`. Can be: `GET` or `POST`.
    :ivar sms_status_callback: The URL we call using a POST method to send status information to your application about SMS messages that refer to the application.
    :ivar sms_url: The URL we call when the phone number receives an incoming SMS message.
    :ivar status_callback: The URL we call using the `status_callback_method` to send status information to your application.
    :ivar status_callback_method: The HTTP method we use to call `status_callback`. Can be: `GET` or `POST`.
    :ivar uri: The URI of the resource, relative to `https://api.twilio.com`.
    :ivar voice_caller_id_lookup: Whether we look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
    :ivar voice_fallback_method: The HTTP method we use to call `voice_fallback_url`. Can be: `GET` or `POST`.
    :ivar voice_fallback_url: The URL that we call when an error occurs retrieving or executing the TwiML requested by `url`.
    :ivar voice_method: The HTTP method we use to call `voice_url`. Can be: `GET` or `POST`.
    :ivar voice_url: The URL we call when the phone number assigned to this application receives a call.
    :ivar public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.
    """
    def __init__(self, version: Version, payload: Dict[str, Any], account_sid: str, sid: Optional[str] = ...) -> None:
        ...
    
    def delete(self) -> bool:
        """
        Deletes the ApplicationInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the ApplicationInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the ApplicationInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the ApplicationInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> ApplicationInstance:
        """
        Fetch the ApplicationInstance


        :returns: The fetched ApplicationInstance
        """
        ...
    
    async def fetch_async(self) -> ApplicationInstance:
        """
        Asynchronous coroutine to fetch the ApplicationInstance


        :returns: The fetched ApplicationInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the ApplicationInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the ApplicationInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Update the ApplicationInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The updated ApplicationInstance
        """
        ...
    
    async def update_async(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Asynchronous coroutine to update the ApplicationInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The updated ApplicationInstance
        """
        ...
    
    def update_with_http_info(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Update the ApplicationInstance with HTTP info

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_with_http_info_async(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the ApplicationInstance with HTTP info

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class ApplicationContext(InstanceContext):
    def __init__(self, version: Version, account_sid: str, sid: str) -> None:
        """
        Initialize the ApplicationContext

        :param version: Version that contains the resource
        :param account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Application resources to update.
        :param sid: The Twilio-provided string that uniquely identifies the Application resource to update.
        """
        ...
    
    def delete(self) -> bool:
        """
        Deletes the ApplicationInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the ApplicationInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the ApplicationInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the ApplicationInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> ApplicationInstance:
        """
        Fetch the ApplicationInstance


        :returns: The fetched ApplicationInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the ApplicationInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> ApplicationInstance:
        """
        Asynchronous coroutine to fetch the ApplicationInstance


        :returns: The fetched ApplicationInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the ApplicationInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Update the ApplicationInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The updated ApplicationInstance
        """
        ...
    
    def update_with_http_info(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Update the ApplicationInstance and return response metadata

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_async(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Asynchronous coroutine to update the ApplicationInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The updated ApplicationInstance
        """
        ...
    
    async def update_with_http_info_async(self, friendly_name: Union[str, object] = ..., api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the ApplicationInstance and return response metadata

        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is your account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: Same as message_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application. Deprecated, included for backwards compatibility.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class ApplicationPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> ApplicationInstance:
        """
        Build an instance of ApplicationInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class ApplicationList(ListResource):
    def __init__(self, version: Version, account_sid: str) -> None:
        """
        Initialize the ApplicationList

        :param version: Version that contains the resource
        :param account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Application resources to read.

        """
        ...
    
    def create(self, api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., friendly_name: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Create the ApplicationInstance

        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is the account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param friendly_name: A descriptive string that you create to describe the new application. It can be up to 64 characters long.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The created ApplicationInstance
        """
        ...
    
    def create_with_http_info(self, api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., friendly_name: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Create the ApplicationInstance and return response metadata

        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is the account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param friendly_name: A descriptive string that you create to describe the new application. It can be up to 64 characters long.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def create_async(self, api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., friendly_name: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApplicationInstance:
        """
        Asynchronously create the ApplicationInstance

        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is the account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param friendly_name: A descriptive string that you create to describe the new application. It can be up to 64 characters long.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: The created ApplicationInstance
        """
        ...
    
    async def create_with_http_info_async(self, api_version: Union[str, object] = ..., voice_url: Union[str, object] = ..., voice_method: Union[str, object] = ..., voice_fallback_url: Union[str, object] = ..., voice_fallback_method: Union[str, object] = ..., status_callback: Union[str, object] = ..., status_callback_method: Union[str, object] = ..., voice_caller_id_lookup: Union[bool, object] = ..., sms_url: Union[str, object] = ..., sms_method: Union[str, object] = ..., sms_fallback_url: Union[str, object] = ..., sms_fallback_method: Union[str, object] = ..., sms_status_callback: Union[str, object] = ..., message_status_callback: Union[str, object] = ..., friendly_name: Union[str, object] = ..., public_application_connect_enabled: Union[bool, object] = ...) -> ApiResponse:
        """
        Asynchronously create the ApplicationInstance and return response metadata

        :param api_version: The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is the account's default API version.
        :param voice_url: The URL we should call when the phone number assigned to this application receives a call.
        :param voice_method: The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
        :param voice_fallback_url: The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
        :param voice_fallback_method: The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
        :param status_callback: The URL we should call using the `status_callback_method` to send status information to your application.
        :param status_callback_method: The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
        :param voice_caller_id_lookup: Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
        :param sms_url: The URL we should call when the phone number receives an incoming SMS message.
        :param sms_method: The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
        :param sms_fallback_url: The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
        :param sms_fallback_method: The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
        :param sms_status_callback: The URL we should call using a POST method to send status information about SMS messages sent by the application.
        :param message_status_callback: The URL we should call using a POST method to send message status information to your application.
        :param friendly_name: A descriptive string that you create to describe the new application. It can be up to 64 characters long.
        :param public_application_connect_enabled: Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def stream(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[ApplicationInstance]:
        """
        Streams ApplicationInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[ApplicationInstance]:
        """
        Asynchronously streams ApplicationInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams ApplicationInstance and returns headers from first page


        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams ApplicationInstance and returns headers from first page


        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[ApplicationInstance]:
        """
        Lists ApplicationInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[ApplicationInstance]:
        """
        Asynchronously lists ApplicationInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists ApplicationInstance and returns headers from first page


        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, friendly_name: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists ApplicationInstance and returns headers from first page


        :param str friendly_name: The string that identifies the Application resources to read.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, friendly_name: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApplicationPage:
        """
        Retrieve a single page of ApplicationInstance records from the API.
        Request is executed immediately

        :param friendly_name: The string that identifies the Application resources to read.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ApplicationInstance
        """
        ...
    
    async def page_async(self, friendly_name: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApplicationPage:
        """
        Asynchronously retrieve a single page of ApplicationInstance records from the API.
        Request is executed immediately

        :param friendly_name: The string that identifies the Application resources to read.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ApplicationInstance
        """
        ...
    
    def page_with_http_info(self, friendly_name: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param friendly_name: The string that identifies the Application resources to read.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ApplicationPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, friendly_name: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param friendly_name: The string that identifies the Application resources to read.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ApplicationPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> ApplicationPage:
        """
        Retrieve a specific page of ApplicationInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ApplicationInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> ApplicationPage:
        """
        Asynchronously retrieve a specific page of ApplicationInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ApplicationInstance
        """
        ...
    
    def get(self, sid: str) -> ApplicationContext:
        """
        Constructs a ApplicationContext

        :param sid: The Twilio-provided string that uniquely identifies the Application resource to update.
        """
        ...
    
    def __call__(self, sid: str) -> ApplicationContext:
        """
        Constructs a ApplicationContext

        :param sid: The Twilio-provided string that uniquely identifies the Application resource to update.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


