"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Api
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class AuthorizedConnectAppInstance(InstanceResource):
    class Permission:
        GET_ALL = ...
        POST_ALL = ...
    
    
    def __init__(self, version: Version, payload: Dict[str, Any], account_sid: str, connect_app_sid: Optional[str] = ...) -> None:
        ...
    
    def fetch(self) -> AuthorizedConnectAppInstance:
        """
        Fetch the AuthorizedConnectAppInstance


        :returns: The fetched AuthorizedConnectAppInstance
        """
        ...
    
    async def fetch_async(self) -> AuthorizedConnectAppInstance:
        """
        Asynchronous coroutine to fetch the AuthorizedConnectAppInstance


        :returns: The fetched AuthorizedConnectAppInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the AuthorizedConnectAppInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the AuthorizedConnectAppInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class AuthorizedConnectAppContext(InstanceContext):
    def __init__(self, version: Version, account_sid: str, connect_app_sid: str) -> None:
        """
        Initialize the AuthorizedConnectAppContext

        :param version: Version that contains the resource
        :param account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AuthorizedConnectApp resource to fetch.
        :param connect_app_sid: The SID of the Connect App to fetch.
        """
        ...
    
    def fetch(self) -> AuthorizedConnectAppInstance:
        """
        Fetch the AuthorizedConnectAppInstance


        :returns: The fetched AuthorizedConnectAppInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the AuthorizedConnectAppInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> AuthorizedConnectAppInstance:
        """
        Asynchronous coroutine to fetch the AuthorizedConnectAppInstance


        :returns: The fetched AuthorizedConnectAppInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the AuthorizedConnectAppInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class AuthorizedConnectAppPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> AuthorizedConnectAppInstance:
        """
        Build an instance of AuthorizedConnectAppInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class AuthorizedConnectAppList(ListResource):
    def __init__(self, version: Version, account_sid: str) -> None:
        """
        Initialize the AuthorizedConnectAppList

        :param version: Version that contains the resource
        :param account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AuthorizedConnectApp resources to read.

        """
        ...
    
    def stream(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[AuthorizedConnectAppInstance]:
        """
        Streams AuthorizedConnectAppInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[AuthorizedConnectAppInstance]:
        """
        Asynchronously streams AuthorizedConnectAppInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams AuthorizedConnectAppInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams AuthorizedConnectAppInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[AuthorizedConnectAppInstance]:
        """
        Lists AuthorizedConnectAppInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[AuthorizedConnectAppInstance]:
        """
        Asynchronously lists AuthorizedConnectAppInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists AuthorizedConnectAppInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists AuthorizedConnectAppInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> AuthorizedConnectAppPage:
        """
        Retrieve a single page of AuthorizedConnectAppInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizedConnectAppInstance
        """
        ...
    
    async def page_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> AuthorizedConnectAppPage:
        """
        Asynchronously retrieve a single page of AuthorizedConnectAppInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizedConnectAppInstance
        """
        ...
    
    def page_with_http_info(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizedConnectAppPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizedConnectAppPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> AuthorizedConnectAppPage:
        """
        Retrieve a specific page of AuthorizedConnectAppInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizedConnectAppInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> AuthorizedConnectAppPage:
        """
        Asynchronously retrieve a specific page of AuthorizedConnectAppInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizedConnectAppInstance
        """
        ...
    
    def get(self, connect_app_sid: str) -> AuthorizedConnectAppContext:
        """
        Constructs a AuthorizedConnectAppContext

        :param connect_app_sid: The SID of the Connect App to fetch.
        """
        ...
    
    def __call__(self, connect_app_sid: str) -> AuthorizedConnectAppContext:
        """
        Constructs a AuthorizedConnectAppContext

        :param connect_app_sid: The SID of the Connect App to fetch.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


