"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Serverless
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class LogInstance(InstanceResource):
    """
    :ivar sid: The unique string that we created to identify the Log resource.
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Log resource.
    :ivar service_sid: The SID of the Service that the Log resource is associated with.
    :ivar environment_sid: The SID of the environment in which the log occurred.
    :ivar build_sid: The SID of the build that corresponds to the log.
    :ivar deployment_sid: The SID of the deployment that corresponds to the log.
    :ivar function_sid: The SID of the function whose invocation produced the log.
    :ivar request_sid: The SID of the request associated with the log.
    :ivar level: The log level.
    :ivar message: The log message.
    :ivar date_created: The date and time in GMT when the Log resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    :ivar url: The absolute URL of the Log resource.
    """
    def __init__(self, version: Version, payload: Dict[str, Any], service_sid: str, environment_sid: str, sid: Optional[str] = ...) -> None:
        ...
    
    def fetch(self) -> LogInstance:
        """
        Fetch the LogInstance


        :returns: The fetched LogInstance
        """
        ...
    
    async def fetch_async(self) -> LogInstance:
        """
        Asynchronous coroutine to fetch the LogInstance


        :returns: The fetched LogInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the LogInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the LogInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class LogContext(InstanceContext):
    def __init__(self, version: Version, service_sid: str, environment_sid: str, sid: str) -> None:
        """
        Initialize the LogContext

        :param version: Version that contains the resource
        :param service_sid: The SID of the Service to fetch the Log resource from.
        :param environment_sid: The SID of the environment with the Log resource to fetch.
        :param sid: The SID of the Log resource to fetch.
        """
        ...
    
    def fetch(self) -> LogInstance:
        """
        Fetch the LogInstance


        :returns: The fetched LogInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the LogInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> LogInstance:
        """
        Asynchronous coroutine to fetch the LogInstance


        :returns: The fetched LogInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the LogInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class LogPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> LogInstance:
        """
        Build an instance of LogInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class LogList(ListResource):
    def __init__(self, version: Version, service_sid: str, environment_sid: str) -> None:
        """
        Initialize the LogList

        :param version: Version that contains the resource
        :param service_sid: The SID of the Service to read the Log resource from.
        :param environment_sid: The SID of the environment with the Log resources to read.

        """
        ...
    
    def stream(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[LogInstance]:
        """
        Streams LogInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[LogInstance]:
        """
        Asynchronously streams LogInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams LogInstance and returns headers from first page


        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams LogInstance and returns headers from first page


        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[LogInstance]:
        """
        Lists LogInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[LogInstance]:
        """
        Asynchronously lists LogInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists LogInstance and returns headers from first page


        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists LogInstance and returns headers from first page


        :param str function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param datetime start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param datetime end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> LogPage:
        """
        Retrieve a single page of LogInstance records from the API.
        Request is executed immediately

        :param function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        ...
    
    async def page_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> LogPage:
        """
        Asynchronously retrieve a single page of LogInstance records from the API.
        Request is executed immediately

        :param function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        ...
    
    def page_with_http_info(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, function_sid: Union[str, object] = ..., start_date: Union[datetime, object] = ..., end_date: Union[datetime, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param function_sid: The SID of the function whose invocation produced the Log resources to read.
        :param start_date: The date/time (in GMT, ISO 8601) after which the Log resources must have been created. Defaults to 1 day prior to current date/time.
        :param end_date: The date/time (in GMT, ISO 8601) before which the Log resources must have been created. Defaults to current date/time.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> LogPage:
        """
        Retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> LogPage:
        """
        Asynchronously retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        ...
    
    def get(self, sid: str) -> LogContext:
        """
        Constructs a LogContext

        :param sid: The SID of the Log resource to fetch.
        """
        ...
    
    def __call__(self, sid: str) -> LogContext:
        """
        Constructs a LogContext

        :param sid: The SID of the Log resource to fetch.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


