"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Numbers
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class PortingPortInInstance(InstanceResource):
    class NumbersV1PortingAddress:
        """
        :ivar street: The street address, ex: 101 Spear St
        :ivar street_2: The building information, ex : 5th floor.
        :ivar city: The city name, ex: San Francisco.
        :ivar state: The state name, ex: CA or California. Note this should match the losing carrier’s information exactly. So if they spell out the entire state’s name instead of abbreviating it, please do so.
        :ivar zip: The zip code, ex: 94105.
        :ivar country: The country, ex: USA.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    class NumbersV1PortingLosingCarrierInformation:
        """
        :ivar customer_name: Customer name as it is registered with the losing carrier. This can be an individual or a business name depending on the customer type selected.
        :ivar account_number: The account number of the customer for the losing carrier. Only require for mobile phone numbers.
        :ivar account_telephone_number: The account phone number of the customer for the losing carrier.
        :ivar address_sid: If you already have an Address SID that represents the address needed for the LOA, you can provide an Address SID instead of providing the address object in the request body. This will copy the address into the port in request. If changes are made to the Address SID after port in request creation, those changes will not be reflected in the port in request.
        :ivar address:
        :ivar authorized_representative: The first and last name of the person listed with the losing carrier who is authorized to make changes on the account.
        :ivar authorized_representative_email: Email address of the person (owner of the number) who will sign the letter of authorization for the port in request. This email address should belong to the person named in as the authorized representative.
        :ivar customer_type: The type of customer account in the losing carrier. This should either be: 'Individual' or 'Business'.
        :ivar authorized_representative_katakana:
        :ivar sub_municipality:
        :ivar building:
        :ivar katakana_name:
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreate:
        """
        :ivar account_sid: Account Sid or subaccount where the phone number(s) will be Ported
        :ivar documents: List of document SIDs for all phone numbers included in the port in request. At least one document SID referring to a document of the type Utility Bill is required.
        :ivar phone_numbers: List of phone numbers to be ported. Maximum of 1,000 phone numbers per request.
        :ivar losing_carrier_information:
        :ivar notification_emails: Additional emails to send a copy of the signed LOA to.
        :ivar target_port_in_date: Target date to port the number. We cannot guarantee that this date will be honored by the other carriers, please work with Ops to get a confirmation of the firm order commitment (FOC) date. Expected format is ISO Local Date, example: ‘2011-12-03`. This date must be at least 7 days in the future for US ports and 10 days in the future for Japanese ports. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_start: The earliest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_end: The latest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar bundle_sid: The bundle sid is an optional identifier to reference a group of regulatory documents for a port request.
        :ivar portability_advance_carrier: A field only required for Japan port in requests. It is a unique identifier for the donor carrier service the line is being ported from.
        :ivar auto_cancel_approval_numbers: Japan specific field, indicates the number of phone numbers to automatically approve for cancellation.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreatePhoneNumbers:
        """
        :ivar phone_number: Phone number to be ported. This must be in the E164 Format.
        :ivar pin: Some losing carriers require a PIN to authorize the port of a phone number. If the phone number is a US mobile phone number, the PIN is mandatory to process a porting request. Other carriers and number types may also require a PIN, you'll need to contact the losing carrier to determine what your phone number's PIN is.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    def __init__(self, version: Version, payload: Dict[str, Any], port_in_request_sid: Optional[str] = ...) -> None:
        ...
    
    def delete(self) -> bool:
        """
        Deletes the PortingPortInInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the PortingPortInInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the PortingPortInInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the PortingPortInInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> PortingPortInInstance:
        """
        Fetch the PortingPortInInstance


        :returns: The fetched PortingPortInInstance
        """
        ...
    
    async def fetch_async(self) -> PortingPortInInstance:
        """
        Asynchronous coroutine to fetch the PortingPortInInstance


        :returns: The fetched PortingPortInInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the PortingPortInInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the PortingPortInInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class PortingPortInContext(InstanceContext):
    class NumbersV1PortingAddress:
        """
        :ivar street: The street address, ex: 101 Spear St
        :ivar street_2: The building information, ex : 5th floor.
        :ivar city: The city name, ex: San Francisco.
        :ivar state: The state name, ex: CA or California. Note this should match the losing carrier’s information exactly. So if they spell out the entire state’s name instead of abbreviating it, please do so.
        :ivar zip: The zip code, ex: 94105.
        :ivar country: The country, ex: USA.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    class NumbersV1PortingLosingCarrierInformation:
        """
        :ivar customer_name: Customer name as it is registered with the losing carrier. This can be an individual or a business name depending on the customer type selected.
        :ivar account_number: The account number of the customer for the losing carrier. Only require for mobile phone numbers.
        :ivar account_telephone_number: The account phone number of the customer for the losing carrier.
        :ivar address_sid: If you already have an Address SID that represents the address needed for the LOA, you can provide an Address SID instead of providing the address object in the request body. This will copy the address into the port in request. If changes are made to the Address SID after port in request creation, those changes will not be reflected in the port in request.
        :ivar address:
        :ivar authorized_representative: The first and last name of the person listed with the losing carrier who is authorized to make changes on the account.
        :ivar authorized_representative_email: Email address of the person (owner of the number) who will sign the letter of authorization for the port in request. This email address should belong to the person named in as the authorized representative.
        :ivar customer_type: The type of customer account in the losing carrier. This should either be: 'Individual' or 'Business'.
        :ivar authorized_representative_katakana:
        :ivar sub_municipality:
        :ivar building:
        :ivar katakana_name:
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreate:
        """
        :ivar account_sid: Account Sid or subaccount where the phone number(s) will be Ported
        :ivar documents: List of document SIDs for all phone numbers included in the port in request. At least one document SID referring to a document of the type Utility Bill is required.
        :ivar phone_numbers: List of phone numbers to be ported. Maximum of 1,000 phone numbers per request.
        :ivar losing_carrier_information:
        :ivar notification_emails: Additional emails to send a copy of the signed LOA to.
        :ivar target_port_in_date: Target date to port the number. We cannot guarantee that this date will be honored by the other carriers, please work with Ops to get a confirmation of the firm order commitment (FOC) date. Expected format is ISO Local Date, example: ‘2011-12-03`. This date must be at least 7 days in the future for US ports and 10 days in the future for Japanese ports. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_start: The earliest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_end: The latest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar bundle_sid: The bundle sid is an optional identifier to reference a group of regulatory documents for a port request.
        :ivar portability_advance_carrier: A field only required for Japan port in requests. It is a unique identifier for the donor carrier service the line is being ported from.
        :ivar auto_cancel_approval_numbers: Japan specific field, indicates the number of phone numbers to automatically approve for cancellation.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreatePhoneNumbers:
        """
        :ivar phone_number: Phone number to be ported. This must be in the E164 Format.
        :ivar pin: Some losing carriers require a PIN to authorize the port of a phone number. If the phone number is a US mobile phone number, the PIN is mandatory to process a porting request. Other carriers and number types may also require a PIN, you'll need to contact the losing carrier to determine what your phone number's PIN is.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    def __init__(self, version: Version, port_in_request_sid: str) -> None:
        """
        Initialize the PortingPortInContext

        :param version: Version that contains the resource
        :param port_in_request_sid: The SID of the Port In request. This is a unique identifier of the port in request.
        """
        ...
    
    def delete(self) -> bool:
        """
        Deletes the PortingPortInInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the PortingPortInInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the PortingPortInInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the PortingPortInInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> PortingPortInInstance:
        """
        Fetch the PortingPortInInstance


        :returns: The fetched PortingPortInInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the PortingPortInInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> PortingPortInInstance:
        """
        Asynchronous coroutine to fetch the PortingPortInInstance


        :returns: The fetched PortingPortInInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the PortingPortInInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class PortingPortInList(ListResource):
    class NumbersV1PortingAddress:
        """
        :ivar street: The street address, ex: 101 Spear St
        :ivar street_2: The building information, ex : 5th floor.
        :ivar city: The city name, ex: San Francisco.
        :ivar state: The state name, ex: CA or California. Note this should match the losing carrier’s information exactly. So if they spell out the entire state’s name instead of abbreviating it, please do so.
        :ivar zip: The zip code, ex: 94105.
        :ivar country: The country, ex: USA.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    class NumbersV1PortingLosingCarrierInformation:
        """
        :ivar customer_name: Customer name as it is registered with the losing carrier. This can be an individual or a business name depending on the customer type selected.
        :ivar account_number: The account number of the customer for the losing carrier. Only require for mobile phone numbers.
        :ivar account_telephone_number: The account phone number of the customer for the losing carrier.
        :ivar address_sid: If you already have an Address SID that represents the address needed for the LOA, you can provide an Address SID instead of providing the address object in the request body. This will copy the address into the port in request. If changes are made to the Address SID after port in request creation, those changes will not be reflected in the port in request.
        :ivar address:
        :ivar authorized_representative: The first and last name of the person listed with the losing carrier who is authorized to make changes on the account.
        :ivar authorized_representative_email: Email address of the person (owner of the number) who will sign the letter of authorization for the port in request. This email address should belong to the person named in as the authorized representative.
        :ivar customer_type: The type of customer account in the losing carrier. This should either be: 'Individual' or 'Business'.
        :ivar authorized_representative_katakana:
        :ivar sub_municipality:
        :ivar building:
        :ivar katakana_name:
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreate:
        """
        :ivar account_sid: Account Sid or subaccount where the phone number(s) will be Ported
        :ivar documents: List of document SIDs for all phone numbers included in the port in request. At least one document SID referring to a document of the type Utility Bill is required.
        :ivar phone_numbers: List of phone numbers to be ported. Maximum of 1,000 phone numbers per request.
        :ivar losing_carrier_information:
        :ivar notification_emails: Additional emails to send a copy of the signed LOA to.
        :ivar target_port_in_date: Target date to port the number. We cannot guarantee that this date will be honored by the other carriers, please work with Ops to get a confirmation of the firm order commitment (FOC) date. Expected format is ISO Local Date, example: ‘2011-12-03`. This date must be at least 7 days in the future for US ports and 10 days in the future for Japanese ports. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_start: The earliest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar target_port_in_time_range_end: The latest time that the port should occur on the target port in date. Expected format is ISO Offset Time, example: ‘10:15:00-08:00'. We can't guarantee the exact date and time, as this depends on the losing carrier
        :ivar bundle_sid: The bundle sid is an optional identifier to reference a group of regulatory documents for a port request.
        :ivar portability_advance_carrier: A field only required for Japan port in requests. It is a unique identifier for the donor carrier service the line is being ported from.
        :ivar auto_cancel_approval_numbers: Japan specific field, indicates the number of phone numbers to automatically approve for cancellation.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, Any]:
            ...
        
    
    
    class NumbersV1PortingPortInCreatePhoneNumbers:
        """
        :ivar phone_number: Phone number to be ported. This must be in the E164 Format.
        :ivar pin: Some losing carriers require a PIN to authorize the port of a phone number. If the phone number is a US mobile phone number, the PIN is mandatory to process a porting request. Other carriers and number types may also require a PIN, you'll need to contact the losing carrier to determine what your phone number's PIN is.
        """
        def __init__(self, payload: Dict[str, Any]) -> None:
            ...
        
        def to_dict(self): # -> dict[str, str | None]:
            ...
        
    
    
    def __init__(self, version: Version) -> None:
        """
        Initialize the PortingPortInList

        :param version: Version that contains the resource

        """
        ...
    
    def create(self, numbers_v1_porting_port_in_create: NumbersV1PortingPortInCreate) -> PortingPortInInstance:
        """
        Create the PortingPortInInstance

        :param numbers_v1_porting_port_in_create:

        :returns: The created PortingPortInInstance
        """
        ...
    
    def create_with_http_info(self, numbers_v1_porting_port_in_create: NumbersV1PortingPortInCreate) -> ApiResponse:
        """
        Create the PortingPortInInstance and return response metadata

        :param numbers_v1_porting_port_in_create:

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def create_async(self, numbers_v1_porting_port_in_create: NumbersV1PortingPortInCreate) -> PortingPortInInstance:
        """
        Asynchronously create the PortingPortInInstance

        :param numbers_v1_porting_port_in_create:

        :returns: The created PortingPortInInstance
        """
        ...
    
    async def create_with_http_info_async(self, numbers_v1_porting_port_in_create: NumbersV1PortingPortInCreate) -> ApiResponse:
        """
        Asynchronously create the PortingPortInInstance and return response metadata

        :param numbers_v1_porting_port_in_create:

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def get(self, port_in_request_sid: str) -> PortingPortInContext:
        """
        Constructs a PortingPortInContext

        :param port_in_request_sid: The SID of the Port In request. This is a unique identifier of the port in request.
        """
        ...
    
    def __call__(self, port_in_request_sid: str) -> PortingPortInContext:
        """
        Constructs a PortingPortInContext

        :param port_in_request_sid: The SID of the Port In request. This is a unique identifier of the port in request.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


