"""
This type stub file was generated by pyright.
"""

from warnings import warn
from twilio.rest.taskrouter.TaskrouterBase import TaskrouterBase
from twilio.rest.taskrouter.v1.workspace import WorkspaceList

class Taskrouter(TaskrouterBase):
    @property
    def workspaces(self) -> WorkspaceList:
        ...
    


