"""
This type stub file was generated by pyright.
"""

from twilio.base.domain import Domain
from twilio.rest import Client
from twilio.rest.lookups.v1 import V1
from twilio.rest.lookups.v2 import V2

r"""
  This code was generated by
  ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
   |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
   |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""
class LookupsBase(Domain):
    def __init__(self, twilio: Client) -> None:
        """
        Initialize the Lookups Domain

        :returns: Domain for Lookups
        """
        ...
    
    @property
    def v1(self) -> V1:
        """
        :returns: Versions v1 of Lookups
        """
        ...
    
    @property
    def v2(self) -> V2:
        """
        :returns: Versions v2 of Lookups
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        ...
    


