"""
This type stub file was generated by pyright.
"""

from typing import Optional
from twilio.base.version import Version
from twilio.base.domain import Domain
from twilio.rest.assistants.v1.assistant import AssistantList
from twilio.rest.assistants.v1.knowledge import KnowledgeList
from twilio.rest.assistants.v1.policy import PolicyList
from twilio.rest.assistants.v1.session import SessionList
from twilio.rest.assistants.v1.tool import ToolList

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Assistants
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class V1(Version):
    def __init__(self, domain: Domain) -> None:
        """
        Initialize the V1 version of Assistants

        :param domain: The Twilio.assistants domain
        """
        ...
    
    @property
    def assistants(self) -> AssistantList:
        ...
    
    @property
    def knowledge(self) -> KnowledgeList:
        ...
    
    @property
    def policies(self) -> PolicyList:
        ...
    
    @property
    def sessions(self) -> SessionList:
        ...
    
    @property
    def tools(self) -> ToolList:
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        ...
    


