"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Assistants
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class PolicyInstance(InstanceResource):
    """
    :ivar id: The Policy ID.
    :ivar name: The name of the policy.
    :ivar description: The description of the policy.
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Policy resource.
    :ivar user_sid: The SID of the User that created the Policy resource.
    :ivar type: The type of the policy.
    :ivar policy_details: The details of the policy based on the type.
    :ivar date_created: The date and time in GMT when the Policy was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    :ivar date_updated: The date and time in GMT when the Policy was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    """
    def __init__(self, version: Version, payload: Dict[str, Any]) -> None:
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class PolicyPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> PolicyInstance:
        """
        Build an instance of PolicyInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class PolicyList(ListResource):
    def __init__(self, version: Version) -> None:
        """
        Initialize the PolicyList

        :param version: Version that contains the resource

        """
        ...
    
    def stream(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[PolicyInstance]:
        """
        Streams PolicyInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[PolicyInstance]:
        """
        Asynchronously streams PolicyInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams PolicyInstance and returns headers from first page


        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams PolicyInstance and returns headers from first page


        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[PolicyInstance]:
        """
        Lists PolicyInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[PolicyInstance]:
        """
        Asynchronously lists PolicyInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists PolicyInstance and returns headers from first page


        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists PolicyInstance and returns headers from first page


        :param str tool_id: The tool ID.
        :param str knowledge_id: The knowledge ID.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> PolicyPage:
        """
        Retrieve a single page of PolicyInstance records from the API.
        Request is executed immediately

        :param tool_id: The tool ID.
        :param knowledge_id: The knowledge ID.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of PolicyInstance
        """
        ...
    
    async def page_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> PolicyPage:
        """
        Asynchronously retrieve a single page of PolicyInstance records from the API.
        Request is executed immediately

        :param tool_id: The tool ID.
        :param knowledge_id: The knowledge ID.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of PolicyInstance
        """
        ...
    
    def page_with_http_info(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param tool_id: The tool ID.
        :param knowledge_id: The knowledge ID.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with PolicyPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, tool_id: Union[str, object] = ..., knowledge_id: Union[str, object] = ..., page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param tool_id: The tool ID.
        :param knowledge_id: The knowledge ID.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with PolicyPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> PolicyPage:
        """
        Retrieve a specific page of PolicyInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of PolicyInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> PolicyPage:
        """
        Asynchronously retrieve a specific page of PolicyInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of PolicyInstance
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


