"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base import deserialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page
from twilio.rest.conversations.v1.service.user.user_conversation import UserConversationList

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Conversations
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class UserInstance(InstanceResource):
    class WebhookEnabledType:
        TRUE = ...
        FALSE = ...
    
    
    def __init__(self, version: Version, payload: Dict[str, Any], chat_service_sid: str, sid: Optional[str] = ...) -> None:
        ...
    
    def delete(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> bool:
        """
        Deletes the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> bool:
        """
        Asynchronous coroutine that deletes the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> ApiResponse:
        """
        Deletes the UserInstance with HTTP info

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_with_http_info_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the UserInstance with HTTP info

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> UserInstance:
        """
        Fetch the UserInstance


        :returns: The fetched UserInstance
        """
        ...
    
    async def fetch_async(self) -> UserInstance:
        """
        Asynchronous coroutine to fetch the UserInstance


        :returns: The fetched UserInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the UserInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the UserInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Update the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The updated UserInstance
        """
        ...
    
    async def update_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Asynchronous coroutine to update the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The updated UserInstance
        """
        ...
    
    def update_with_http_info(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Update the UserInstance with HTTP info

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_with_http_info_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the UserInstance with HTTP info

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    @property
    def user_conversations(self) -> UserConversationList:
        """
        Access the user_conversations
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class UserContext(InstanceContext):
    def __init__(self, version: Version, chat_service_sid: str, sid: str) -> None:
        """
        Initialize the UserContext

        :param version: Version that contains the resource
        :param chat_service_sid: The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the User resource is associated with.
        :param sid: The SID of the User resource to update. This value can be either the `sid` or the `identity` of the User resource to update.
        """
        ...
    
    def delete(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> bool:
        """
        Deletes the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> ApiResponse:
        """
        Deletes the UserInstance and return response metadata

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> bool:
        """
        Asynchronous coroutine that deletes the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_with_http_info_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the UserInstance and return response metadata

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header

        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> UserInstance:
        """
        Fetch the UserInstance


        :returns: The fetched UserInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the UserInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> UserInstance:
        """
        Asynchronous coroutine to fetch the UserInstance


        :returns: The fetched UserInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the UserInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Update the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The updated UserInstance
        """
        ...
    
    def update_with_http_info(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Update the UserInstance and return response metadata

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Asynchronous coroutine to update the UserInstance

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The updated UserInstance
        """
        ...
    
    async def update_with_http_info_async(self, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the UserInstance and return response metadata

        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    @property
    def user_conversations(self) -> UserConversationList:
        """
        Access the user_conversations
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class UserPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> UserInstance:
        """
        Build an instance of UserInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class UserList(ListResource):
    def __init__(self, version: Version, chat_service_sid: str) -> None:
        """
        Initialize the UserList

        :param version: Version that contains the resource
        :param chat_service_sid: The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) to read the User resources from.

        """
        ...
    
    def create(self, identity: str, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Create the UserInstance

        :param identity: The application-defined string that uniquely identifies the resource's User within the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource). This value is often a username or an email address, and is case-sensitive.
        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The created UserInstance
        """
        ...
    
    def create_with_http_info(self, identity: str, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Create the UserInstance and return response metadata

        :param identity: The application-defined string that uniquely identifies the resource's User within the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource). This value is often a username or an email address, and is case-sensitive.
        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def create_async(self, identity: str, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> UserInstance:
        """
        Asynchronously create the UserInstance

        :param identity: The application-defined string that uniquely identifies the resource's User within the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource). This value is often a username or an email address, and is case-sensitive.
        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: The created UserInstance
        """
        ...
    
    async def create_with_http_info_async(self, identity: str, x_twilio_webhook_enabled: Union[UserInstance.WebhookEnabledType, object] = ..., friendly_name: Union[str, object] = ..., attributes: Union[str, object] = ..., role_sid: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronously create the UserInstance and return response metadata

        :param identity: The application-defined string that uniquely identifies the resource's User within the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource). This value is often a username or an email address, and is case-sensitive.
        :param x_twilio_webhook_enabled: The X-Twilio-Webhook-Enabled HTTP request header
        :param friendly_name: The string that you assigned to describe the resource.
        :param attributes: The JSON Object string that stores application-specific data. If attributes have not been set, `{}` is returned.
        :param role_sid: The SID of a service-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the user.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def stream(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[UserInstance]:
        """
        Streams UserInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[UserInstance]:
        """
        Asynchronously streams UserInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams UserInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams UserInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[UserInstance]:
        """
        Lists UserInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[UserInstance]:
        """
        Asynchronously lists UserInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists UserInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists UserInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> UserPage:
        """
        Retrieve a single page of UserInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of UserInstance
        """
        ...
    
    async def page_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> UserPage:
        """
        Asynchronously retrieve a single page of UserInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of UserInstance
        """
        ...
    
    def page_with_http_info(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with UserPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with UserPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> UserPage:
        """
        Retrieve a specific page of UserInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of UserInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> UserPage:
        """
        Asynchronously retrieve a specific page of UserInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of UserInstance
        """
        ...
    
    def get(self, sid: str) -> UserContext:
        """
        Constructs a UserContext

        :param sid: The SID of the User resource to update. This value can be either the `sid` or the `identity` of the User resource to update.
        """
        ...
    
    def __call__(self, sid: str) -> UserContext:
        """
        Constructs a UserContext

        :param sid: The SID of the User resource to update. This value can be either the `sid` or the `identity` of the User resource to update.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


