"""
This type stub file was generated by pyright.
"""

from warnings import warn
from twilio.rest.preview.PreviewBase import PreviewBase
from twilio.rest.preview.hosted_numbers.authorization_document import AuthorizationDocumentList
from twilio.rest.preview.hosted_numbers.hosted_number_order import HostedNumberOrderList
from twilio.rest.preview.marketplace.available_add_on import AvailableAddOnList
from twilio.rest.preview.marketplace.installed_add_on import InstalledAddOnList
from twilio.rest.preview.wireless.command import CommandList
from twilio.rest.preview.wireless.rate_plan import RatePlanList
from twilio.rest.preview.wireless.sim import SimList

class Preview(PreviewBase):
    @property
    def authorization_documents(self) -> AuthorizationDocumentList:
        ...
    
    @property
    def hosted_number_orders(self) -> HostedNumberOrderList:
        ...
    
    @property
    def available_add_ons(self) -> AvailableAddOnList:
        ...
    
    @property
    def installed_add_ons(self) -> InstalledAddOnList:
        ...
    
    @property
    def commands(self) -> CommandList:
        ...
    
    @property
    def rate_plans(self) -> RatePlanList:
        ...
    
    @property
    def sims(self) -> SimList:
        ...
    


