"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Intelligence
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class MediaInstance(InstanceResource):
    """
    :ivar account_sid: The unique SID identifier of the Account.
    :ivar media_url: Downloadable URL for media, if stored in Twilio AI.
    :ivar service_sid: The unique SID identifier of the Service.
    :ivar sid: The unique SID identifier of the Transcript.
    :ivar url: The URL of this resource.
    """
    def __init__(self, version: Version, payload: Dict[str, Any], sid: str) -> None:
        ...
    
    def fetch(self, redacted: Union[bool, object] = ...) -> MediaInstance:
        """
        Fetch the MediaInstance

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: The fetched MediaInstance
        """
        ...
    
    async def fetch_async(self, redacted: Union[bool, object] = ...) -> MediaInstance:
        """
        Asynchronous coroutine to fetch the MediaInstance

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: The fetched MediaInstance
        """
        ...
    
    def fetch_with_http_info(self, redacted: Union[bool, object] = ...) -> ApiResponse:
        """
        Fetch the MediaInstance with HTTP info

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self, redacted: Union[bool, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the MediaInstance with HTTP info

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class MediaContext(InstanceContext):
    def __init__(self, version: Version, sid: str) -> None:
        """
        Initialize the MediaContext

        :param version: Version that contains the resource
        :param sid: The unique SID identifier of the Transcript.
        """
        ...
    
    def fetch(self, redacted: Union[bool, object] = ...) -> MediaInstance:
        """
        Fetch the MediaInstance

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: The fetched MediaInstance
        """
        ...
    
    def fetch_with_http_info(self, redacted: Union[bool, object] = ...) -> ApiResponse:
        """
        Fetch the MediaInstance and return response metadata

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self, redacted: Union[bool, object] = ...) -> MediaInstance:
        """
        Asynchronous coroutine to fetch the MediaInstance

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: The fetched MediaInstance
        """
        ...
    
    async def fetch_with_http_info_async(self, redacted: Union[bool, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the MediaInstance and return response metadata

        :param redacted: Grant access to PII Redacted/Unredacted Media. If redaction is enabled, the default is `true` to access redacted media.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class MediaList(ListResource):
    def __init__(self, version: Version, sid: str) -> None:
        """
        Initialize the MediaList

        :param version: Version that contains the resource
        :param sid: The unique SID identifier of the Transcript.

        """
        ...
    
    def get(self) -> MediaContext:
        """
        Constructs a MediaContext

        """
        ...
    
    def __call__(self) -> MediaContext:
        """
        Constructs a MediaContext

        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


