"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Trunking
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class OriginationUrlInstance(InstanceResource):
    """
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the OriginationUrl resource.
    :ivar sid: The unique string that we created to identify the OriginationUrl resource.
    :ivar trunk_sid: The SID of the Trunk that owns the Origination URL.
    :ivar weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
    :ivar enabled: Whether the URL is enabled. The default is `true`.
    :ivar sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.
    :ivar friendly_name: The string that you assigned to describe the resource.
    :ivar priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
    :ivar date_created: The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar date_updated: The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar url: The absolute URL of the resource.
    """
    def __init__(self, version: Version, payload: Dict[str, Any], trunk_sid: str, sid: Optional[str] = ...) -> None:
        ...
    
    def delete(self) -> bool:
        """
        Deletes the OriginationUrlInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the OriginationUrlInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the OriginationUrlInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the OriginationUrlInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> OriginationUrlInstance:
        """
        Fetch the OriginationUrlInstance


        :returns: The fetched OriginationUrlInstance
        """
        ...
    
    async def fetch_async(self) -> OriginationUrlInstance:
        """
        Asynchronous coroutine to fetch the OriginationUrlInstance


        :returns: The fetched OriginationUrlInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the OriginationUrlInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the OriginationUrlInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> OriginationUrlInstance:
        """
        Update the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: The updated OriginationUrlInstance
        """
        ...
    
    async def update_async(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> OriginationUrlInstance:
        """
        Asynchronous coroutine to update the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: The updated OriginationUrlInstance
        """
        ...
    
    def update_with_http_info(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> ApiResponse:
        """
        Update the OriginationUrlInstance with HTTP info

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_with_http_info_async(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the OriginationUrlInstance with HTTP info

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OriginationUrlContext(InstanceContext):
    def __init__(self, version: Version, trunk_sid: str, sid: str) -> None:
        """
        Initialize the OriginationUrlContext

        :param version: Version that contains the resource
        :param trunk_sid: The SID of the Trunk from which to update the OriginationUrl.
        :param sid: The unique string that we created to identify the OriginationUrl resource to update.
        """
        ...
    
    def delete(self) -> bool:
        """
        Deletes the OriginationUrlInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the OriginationUrlInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the OriginationUrlInstance


        :returns: True if delete succeeds, False otherwise
        """
        ...
    
    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the OriginationUrlInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        ...
    
    def fetch(self) -> OriginationUrlInstance:
        """
        Fetch the OriginationUrlInstance


        :returns: The fetched OriginationUrlInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the OriginationUrlInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> OriginationUrlInstance:
        """
        Asynchronous coroutine to fetch the OriginationUrlInstance


        :returns: The fetched OriginationUrlInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the OriginationUrlInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def update(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> OriginationUrlInstance:
        """
        Update the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: The updated OriginationUrlInstance
        """
        ...
    
    def update_with_http_info(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> ApiResponse:
        """
        Update the OriginationUrlInstance and return response metadata

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def update_async(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> OriginationUrlInstance:
        """
        Asynchronous coroutine to update the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: The updated OriginationUrlInstance
        """
        ...
    
    async def update_with_http_info_async(self, weight: Union[int, object] = ..., priority: Union[int, object] = ..., enabled: Union[bool, object] = ..., friendly_name: Union[str, object] = ..., sip_url: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronous coroutine to update the OriginationUrlInstance and return response metadata

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema. `sips` is NOT supported.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OriginationUrlPage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> OriginationUrlInstance:
        """
        Build an instance of OriginationUrlInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OriginationUrlList(ListResource):
    def __init__(self, version: Version, trunk_sid: str) -> None:
        """
        Initialize the OriginationUrlList

        :param version: Version that contains the resource
        :param trunk_sid: The SID of the Trunk from which to read the OriginationUrl.

        """
        ...
    
    def create(self, weight: int, priority: int, enabled: bool, friendly_name: str, sip_url: str) -> OriginationUrlInstance:
        """
        Create the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.

        :returns: The created OriginationUrlInstance
        """
        ...
    
    def create_with_http_info(self, weight: int, priority: int, enabled: bool, friendly_name: str, sip_url: str) -> ApiResponse:
        """
        Create the OriginationUrlInstance and return response metadata

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def create_async(self, weight: int, priority: int, enabled: bool, friendly_name: str, sip_url: str) -> OriginationUrlInstance:
        """
        Asynchronously create the OriginationUrlInstance

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.

        :returns: The created OriginationUrlInstance
        """
        ...
    
    async def create_with_http_info_async(self, weight: int, priority: int, enabled: bool, friendly_name: str, sip_url: str) -> ApiResponse:
        """
        Asynchronously create the OriginationUrlInstance and return response metadata

        :param weight: The value that determines the relative share of the load the URI should receive compared to other URIs with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. URLs with higher values receive more load than those with lower ones with the same priority.
        :param priority: The relative importance of the URI. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important URI.
        :param enabled: Whether the URL is enabled. The default is `true`.
        :param friendly_name: A descriptive string that you create to describe the resource. It can be up to 64 characters long.
        :param sip_url: The SIP address you want Twilio to route your Origination calls to. This must be a `sip:` schema.

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def stream(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[OriginationUrlInstance]:
        """
        Streams OriginationUrlInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[OriginationUrlInstance]:
        """
        Asynchronously streams OriginationUrlInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams OriginationUrlInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams OriginationUrlInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[OriginationUrlInstance]:
        """
        Lists OriginationUrlInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[OriginationUrlInstance]:
        """
        Asynchronously lists OriginationUrlInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists OriginationUrlInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists OriginationUrlInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> OriginationUrlPage:
        """
        Retrieve a single page of OriginationUrlInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OriginationUrlInstance
        """
        ...
    
    async def page_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> OriginationUrlPage:
        """
        Asynchronously retrieve a single page of OriginationUrlInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OriginationUrlInstance
        """
        ...
    
    def page_with_http_info(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OriginationUrlPage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OriginationUrlPage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> OriginationUrlPage:
        """
        Retrieve a specific page of OriginationUrlInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OriginationUrlInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> OriginationUrlPage:
        """
        Asynchronously retrieve a specific page of OriginationUrlInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OriginationUrlInstance
        """
        ...
    
    def get(self, sid: str) -> OriginationUrlContext:
        """
        Constructs a OriginationUrlContext

        :param sid: The unique string that we created to identify the OriginationUrl resource to update.
        """
        ...
    
    def __call__(self, sid: str) -> OriginationUrlContext:
        """
        Constructs a OriginationUrlContext

        :param sid: The unique string that we created to identify the OriginationUrl resource to update.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


