"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Intelligence
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class OperatorTypeInstance(InstanceResource):
    class Availability:
        INTERNAL = ...
        BETA = ...
        GENERAL_AVAILABILITY = ...
        RETIRED = ...
        DEPRECATED = ...
    
    
    class OutputType:
        TEXT_CLASSIFICATION = ...
        TEXT_EXTRACTION = ...
        TEXT_EXTRACTION_NORMALIZED = ...
        TEXT_GENERATION = ...
        JSON = ...
    
    
    class Provider:
        TWILIO = ...
        AMAZON = ...
        OPENAI = ...
    
    
    def __init__(self, version: Version, payload: Dict[str, Any], sid: Optional[str] = ...) -> None:
        ...
    
    def fetch(self) -> OperatorTypeInstance:
        """
        Fetch the OperatorTypeInstance


        :returns: The fetched OperatorTypeInstance
        """
        ...
    
    async def fetch_async(self) -> OperatorTypeInstance:
        """
        Asynchronous coroutine to fetch the OperatorTypeInstance


        :returns: The fetched OperatorTypeInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the OperatorTypeInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the OperatorTypeInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OperatorTypeContext(InstanceContext):
    def __init__(self, version: Version, sid: str) -> None:
        """
        Initialize the OperatorTypeContext

        :param version: Version that contains the resource
        :param sid: Either a 34 character string that uniquely identifies this Operator Type or the unique name that references an Operator Type.
        """
        ...
    
    def fetch(self) -> OperatorTypeInstance:
        """
        Fetch the OperatorTypeInstance


        :returns: The fetched OperatorTypeInstance
        """
        ...
    
    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the OperatorTypeInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def fetch_async(self) -> OperatorTypeInstance:
        """
        Asynchronous coroutine to fetch the OperatorTypeInstance


        :returns: The fetched OperatorTypeInstance
        """
        ...
    
    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the OperatorTypeInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OperatorTypePage(Page):
    def get_instance(self, payload: Dict[str, Any]) -> OperatorTypeInstance:
        """
        Build an instance of OperatorTypeInstance

        :param payload: Payload response from the API
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class OperatorTypeList(ListResource):
    def __init__(self, version: Version) -> None:
        """
        Initialize the OperatorTypeList

        :param version: Version that contains the resource

        """
        ...
    
    def stream(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> Iterator[OperatorTypeInstance]:
        """
        Streams OperatorTypeInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    async def stream_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> AsyncIterator[OperatorTypeInstance]:
        """
        Asynchronously streams OperatorTypeInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        ...
    
    def stream_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Streams OperatorTypeInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    async def stream_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> tuple:
        """
        Asynchronously streams OperatorTypeInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        ...
    
    def list(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[OperatorTypeInstance]:
        """
        Lists OperatorTypeInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    async def list_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> List[OperatorTypeInstance]:
        """
        Asynchronously lists OperatorTypeInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        ...
    
    def list_with_http_info(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Lists OperatorTypeInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    async def list_with_http_info_async(self, limit: Optional[int] = ..., page_size: Optional[int] = ...) -> ApiResponse:
        """
        Asynchronously lists OperatorTypeInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        ...
    
    def page(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> OperatorTypePage:
        """
        Retrieve a single page of OperatorTypeInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OperatorTypeInstance
        """
        ...
    
    async def page_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> OperatorTypePage:
        """
        Asynchronously retrieve a single page of OperatorTypeInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OperatorTypeInstance
        """
        ...
    
    def page_with_http_info(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OperatorTypePage, status code, and headers
        """
        ...
    
    async def page_with_http_info_async(self, page_token: Union[str, object] = ..., page_number: Union[int, object] = ..., page_size: Union[int, object] = ...) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OperatorTypePage, status code, and headers
        """
        ...
    
    def get_page(self, target_url: str) -> OperatorTypePage:
        """
        Retrieve a specific page of OperatorTypeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OperatorTypeInstance
        """
        ...
    
    async def get_page_async(self, target_url: str) -> OperatorTypePage:
        """
        Asynchronously retrieve a specific page of OperatorTypeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OperatorTypeInstance
        """
        ...
    
    def get(self, sid: str) -> OperatorTypeContext:
        """
        Constructs a OperatorTypeContext

        :param sid: Either a 34 character string that uniquely identifies this Operator Type or the unique name that references an Operator Type.
        """
        ...
    
    def __call__(self, sid: str) -> OperatorTypeContext:
        """
        Constructs a OperatorTypeContext

        :param sid: Either a 34 character string that uniquely identifies this Operator Type or the unique name that references an Operator Type.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


