"""
This type stub file was generated by pyright.
"""

from warnings import warn
from twilio.rest.bulkexports.BulkexportsBase import BulkexportsBase
from twilio.rest.bulkexports.v1.export import ExportList
from twilio.rest.bulkexports.v1.export_configuration import ExportConfigurationList

class Bulkexports(BulkexportsBase):
    @property
    def exports(self) -> ExportList:
        ...
    
    @property
    def export_configuration(self) -> ExportConfigurationList:
        ...
    


