"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Union
from twilio.base.api_response import ApiResponse
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version

r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Organization Public API
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""
class TokenInstance(InstanceResource):
    """
    :ivar access_token: Token which carries the necessary information to access a Twilio resource directly.
    :ivar refresh_token: Token which carries the information necessary to get a new access token.
    :ivar id_token: Token which carries the information necessary of user profile.
    :ivar token_type: Token type
    :ivar expires_in:
    """
    def __init__(self, version: Version, payload: Dict[str, Any]) -> None:
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


class TokenList(ListResource):
    def __init__(self, version: Version) -> None:
        """
        Initialize the TokenList

        :param version: Version that contains the resource

        """
        ...
    
    def create(self, grant_type: str, client_id: str, client_secret: Union[str, object] = ..., code: Union[str, object] = ..., redirect_uri: Union[str, object] = ..., audience: Union[str, object] = ..., refresh_token: Union[str, object] = ..., scope: Union[str, object] = ...) -> TokenInstance:
        """
        Create the TokenInstance

        :param grant_type: Grant type is a credential representing resource owner's authorization which can be used by client to obtain access token.
        :param client_id: A 34 character string that uniquely identifies this OAuth App.
        :param client_secret: The credential for confidential OAuth App.
        :param code: JWT token related to the authorization code grant type.
        :param redirect_uri: The redirect uri
        :param audience: The targeted audience uri
        :param refresh_token: JWT token related to refresh access token.
        :param scope: The scope of token

        :returns: The created TokenInstance
        """
        ...
    
    def create_with_http_info(self, grant_type: str, client_id: str, client_secret: Union[str, object] = ..., code: Union[str, object] = ..., redirect_uri: Union[str, object] = ..., audience: Union[str, object] = ..., refresh_token: Union[str, object] = ..., scope: Union[str, object] = ...) -> ApiResponse:
        """
        Create the TokenInstance and return response metadata

        :param grant_type: Grant type is a credential representing resource owner's authorization which can be used by client to obtain access token.
        :param client_id: A 34 character string that uniquely identifies this OAuth App.
        :param client_secret: The credential for confidential OAuth App.
        :param code: JWT token related to the authorization code grant type.
        :param redirect_uri: The redirect uri
        :param audience: The targeted audience uri
        :param refresh_token: JWT token related to refresh access token.
        :param scope: The scope of token

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    async def create_async(self, grant_type: str, client_id: str, client_secret: Union[str, object] = ..., code: Union[str, object] = ..., redirect_uri: Union[str, object] = ..., audience: Union[str, object] = ..., refresh_token: Union[str, object] = ..., scope: Union[str, object] = ...) -> TokenInstance:
        """
        Asynchronously create the TokenInstance

        :param grant_type: Grant type is a credential representing resource owner's authorization which can be used by client to obtain access token.
        :param client_id: A 34 character string that uniquely identifies this OAuth App.
        :param client_secret: The credential for confidential OAuth App.
        :param code: JWT token related to the authorization code grant type.
        :param redirect_uri: The redirect uri
        :param audience: The targeted audience uri
        :param refresh_token: JWT token related to refresh access token.
        :param scope: The scope of token

        :returns: The created TokenInstance
        """
        ...
    
    async def create_with_http_info_async(self, grant_type: str, client_id: str, client_secret: Union[str, object] = ..., code: Union[str, object] = ..., redirect_uri: Union[str, object] = ..., audience: Union[str, object] = ..., refresh_token: Union[str, object] = ..., scope: Union[str, object] = ...) -> ApiResponse:
        """
        Asynchronously create the TokenInstance and return response metadata

        :param grant_type: Grant type is a credential representing resource owner's authorization which can be used by client to obtain access token.
        :param client_id: A 34 character string that uniquely identifies this OAuth App.
        :param client_secret: The credential for confidential OAuth App.
        :param code: JWT token related to the authorization code grant type.
        :param redirect_uri: The redirect uri
        :param audience: The targeted audience uri
        :param refresh_token: JWT token related to refresh access token.
        :param scope: The scope of token

        :returns: ApiResponse with instance, status code, and headers
        """
        ...
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        ...
    


